var recommended_tags = ['All','Live','Gaming','Electric vehicles','Computer programming','Music','Apex Legends','Test drives',
'Valorant','Gadgets','Unreal Engine','Motorcycles','Javascript','Gaming community','Exercise','Cinema','Public speaking event',
'Comedy','Hello world','Motorsports','Recently uploaded','Watched','New to you'];

var video_data = 
[
{thumbnail:'assets/thumbnails/twominpapers.webp', channel_dp:'assets/channeldp/twominpapers.jpg', video_title:'OpenAI Plays Hide and Seek...and Breaks The Game!', channel_name:'Two Minute Papers', views:'8.7M views &#183; 3 years ago', video_length: '6:08', hover_src:'assets/videohoveranim/twominpapers.webp'},
{thumbnail:'assets/thumbnails/bikeco.webp', channel_dp:'assets/channeldp/bikeco.jpg', video_title:'Riding the Royal Enfield Hunter 350 in the hills-incredible stock exhaust', channel_name:'BikeCo.', views:'7.7K views &#183; 1 month ago', video_length: '20:26', hover_src:'assets/videohoveranim/bikeco.webp'},
{thumbnail:'assets/thumbnails/eggwick.webp', channel_dp:'assets/channeldp/eggwick.jpg', video_title:'Do these TIKTOK tips actually WORK?', channel_name:'eggwick', views:'58K views &#183; 1 month ago', video_length: '43:19', hover_src:'assets/videohoveranim/eggwick.webp'},
{thumbnail:'assets/thumbnails/sonymusic.webp', channel_dp:'assets/channeldp/sonymusic.jpg', video_title:'Chekka Chivantha Vaanam - Mazhai Kuruvi Lyric (Tamil) | @ ARRahman', channel_name:'Sony Music India', views:'61M views &#183; 4 years ago', video_length: '5:48', hover_src:'assets/videohoveranim/sonymusic.webp'},
{thumbnail:'assets/thumbnails/etaprime.webp', channel_dp:'assets/channeldp/etaprime.jpg', video_title:'We Added A Fast GPU To The Steam Deck! Most Powerful Deck So Far? Hands on Testing', channel_name:'ETA prime', views:'463K views &#183; 8 months ago', video_length: '10:23', hover_src:'assets/videohoveranim/etaprime.webp'},
{thumbnail:'assets/thumbnails/parithabangal.webp', channel_dp:'assets/channeldp/parithabangal.jpg', video_title:'Velinaatu velai paavangal | Parithabangal', channel_name:'Parithabangal', views:'1.2M views &#183; 1 day ago', video_length: '13:48', hover_src:'assets/videohoveranim/parithabangal.webp'},
{thumbnail:'assets/thumbnails/valorant.webp', channel_dp:'assets/channeldp/valorant.jpg', video_title:'Die For You ft.Grabbitz // Official Music Video // Valorant Champions 2021', channel_name:'VALORANT', views:'56M views &#183; 1 year ago', video_length: '3:38', hover_src:'assets/videohoveranim/valorant.webp'},
{thumbnail:'assets/thumbnails/apitamil.webp', channel_dp:'assets/channeldp/apitamil.jpg', video_title:'AR Rahman Hit Songs | Ennai Kaanavillaye Song | Kadhal Desam', channel_name:'API Tamil Songs', views:'75M views &#183; 5 years ago', video_length: '5:47', hover_src:'assets/videohoveranim/apitamil.webp'},
{thumbnail:'assets/thumbnails/hiswattson.webp', channel_dp:'assets/channeldp/hiswattson.jpg', video_title:'WHY #1 PRED THINKS HORIZON IS THE META !?', channel_name:'HisWattson', views:'16K views &#183; 10 days ago', video_length: '9:57', hover_src:'assets/videohoveranim/hiswattson.webp'},
{thumbnail:'assets/thumbnails/eurocarguy.webp', channel_dp:'assets/channeldp/eurocarguy.jpg', video_title:'2021 Mercedes-Maybach S850 | POV NIGHT DRIVE', channel_name:'EUROCARGUY', views:'4.5M views &#183; 1 year ago', video_length: '13:10', hover_src:'assets/videohoveranim/eurocarguy.webp'},
{thumbnail:'assets/thumbnails/district.webp', channel_dp:'assets/channeldp/district.jpg', video_title:'Simple Steps to WIN Fights | Apex Coaching EP:10', channel_name:'District', views:'4.7K views &#183; 17 hours ago', video_length: '15:20', hover_src:'assets/videohoveranim/district.webp'},
{thumbnail:'assets/thumbnails/marko.webp', channel_dp:'assets/channeldp/marko.jpg', video_title:'My New Desk Setup - Day in The Life of a Software Engineer', channel_name:'Marko', views:'84K views &#183; 4 days ago', video_length: '4:24', hover_src:'assets/videohoveranim/marko.webp'},
{thumbnail:'assets/thumbnails/thirupathibrothers.webp', channel_dp:'assets/channeldp/thirupathibrothers.jpg', video_title:'Sathuranga Vettai - Full Tamil Film | Natarajan Subramaniam | Sean Roldan', channel_name:'Thirrupathi Brothers', views:'20M views &#183; 6 years ago', video_length: '2:29:07', hover_src:'assets/videohoveranim/thirupathibrothers.webp'},
{thumbnail:'assets/thumbnails/supersimpledev.webp', channel_dp:'assets/channeldp/supersimpledev.jpg', video_title:'HTML & CSS Full Course - Beginner to Pro (2022)', channel_name:'SuperSimpleDev', views:'2.9M views &#183; 11 months ago', video_length: '6:31:24', hover_src:'assets/videohoveranim/supersimpledev.webp'},
{thumbnail:'assets/thumbnails/motowagon.webp', channel_dp:'assets/channeldp/motowagon.jpg', video_title:"MG's New Hatchback and SUV | Auto Expo 2023 EP-09 | Tamil Review", channel_name:'MotoWagon', views:'6.7k views &#183; 6 hours ago', video_length: '4:55', hover_src:'assets/videohoveranim/motowagon.webp'},
{thumbnail:'assets/thumbnails/autocarindia.webp', channel_dp:'assets/channeldp/autocarindia.jpg', video_title:"Super Nano - The world's fastest Tata Nano! | Track Drive", channel_name:'Autocar India', views:'1M views &#183; 6 years ago', video_length: '5:03', hover_src:'assets/videohoveranim/autocarindia.webp'},
{thumbnail:'assets/thumbnails/raceism.webp', channel_dp:'assets/channeldp/raceism.jpg', video_title:'Raceism 208 Official Film - ILB Drivers Club', channel_name:'ILB Drivers Club', views:'1.6M views &#183; 4 years ago', video_length: '12:36', hover_src:'assets/videohoveranim/raceism.webp'},
{thumbnail:'assets/thumbnails/codelikeme.webp', channel_dp:'assets/channeldp/codelikeme.jpg', video_title:'UE5 Open World - Palm Tree Leaves Wind', channel_name:'CodeLikeMe', views:'240 views &#183; 3 hours ago', video_length: '34:12', hover_src:'assets/videohoveranim/codelikeme.webp'},
{thumbnail:'assets/thumbnails/behindwoodstv.webp', channel_dp:'assets/channeldp/behindwoodstv.jpg', video_title:'இனி சோத்துக்கு என்ன செய்வ!😦கோபத்தில் கொதித்த Seeman 😡சத்தமின்றி உறைந்து போன அரங்கம்😱" aria-label="இனி சோத்துக்கு என்ன செய்வ!😦கோபத்தில் கொதித்த Seeman 😡சத்தமின்றி உறைந்து போன அரங்கம்😱', channel_name:'BehindwoodsTV', views:'4.3M views &#183; 5 months ago', video_length: '14:17', hover_src:'assets/videohoveranim/behindwoodstv.webp'},
{thumbnail:'assets/thumbnails/magnatesmedia.webp', channel_dp:'assets/channeldp/magnatesmedia.jpg', video_title:'Why FedEx Bet Their Entire Company', channel_name:'MagnatesMedia', views:'114K views &#183; 2 days ago', video_length: '19:46', hover_src:'assets/videohoveranim/magnatesmedia.webp'}
];